name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  google_mlkit_text_recognition: ^0.14.0
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.2
  share_plus: ^10.1.2
  receive_sharing_intent: ^1.8.1
  shared_preferences: ^2.2.2
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.10.0
  gal: ^2.3.3
  excel: ^4.0.6
  archive: ^3.6.1
  xml: ^6.6.1
  file_picker: ^10.3.10
  pdf: ^3.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0
  fake_cloud_firestore: ^4.3.0

flutter:
  default-flavor: dev
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/share/
    - assets/splash/
    - assets/avatars/
    - assets/mascot/
    - assets/legal/

# Konfigurasi ikon aplikasi diletakkan di paling bawah
flutter_launcher_icons:
  image_path: "assets/icon/app_icon.png"
  android: true
  ios: true
  image_path_android: "assets/icon/app_icon.png"
