"""Generate the offline Dart dictionary from the supplied XLSX (no dependencies).

Only Keyword, Kategori, Pencocokan, and Sinyal kategori are data inputs.
Notes and instructions inside the workbook are not executed or imported.
"""
import collections
import hashlib
import json
from pathlib import Path
import sys
import xml.etree.ElementTree as ET
import zipfile

source = Path(sys.argv[1])
destination = Path(__file__).resolve().parents[1] / 'lib/data/transaction_keywords.dart'
ns = {'s': 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}
categories = {'Makanan', 'Minuman', 'Jajan', 'Belanja', 'Tagihan & Pulsa', 'Lifestyle', 'Transportasi'}
entries = []
with zipfile.ZipFile(source) as archive:
    strings = []
    if 'xl/sharedStrings.xml' in archive.namelist():
        strings = [''.join(node.itertext()) for node in
                   ET.fromstring(archive.read('xl/sharedStrings.xml')).findall('s:si', ns)]
    for name in sorted(archive.namelist()):
        if not (name.startswith('xl/worksheets/sheet') and name.endswith('.xml')):
            continue
        rows = []
        for row in ET.fromstring(archive.read(name)).findall('.//s:row', ns):
            cells = {}
            for cell in row.findall('s:c', ns):
                column = ''.join(c for c in cell.attrib['r'] if c.isalpha())
                value = cell.find('s:v', ns)
                inline = cell.find('s:is', ns)
                text = value.text if value is not None else ''.join(inline.itertext()) if inline is not None else ''
                cells[column] = strings[int(text)] if cell.get('t') == 's' else text
            rows.append(cells)
        assert rows[0]['B'] == 'Keyword' and rows[0]['C'] == 'Kategori'
        for row in rows[1:]:
            keyword = row['B'].strip().lower()
            category = row['C'].replace('Tagihan & pulsa', 'Tagihan & Pulsa')
            assert category in categories and keyword
            assert row['D'] in ('kata utuh', 'frasa utuh')
            strength = {'Kuat': 3, 'Sedang': 2, 'Kontekstual': 1}[row['E']]
            entries.append((keyword, category, strength))
assert len(entries) == 1400 and len({e[0] for e in entries}) == 1400
quote = lambda value: json.dumps(value, ensure_ascii=False).replace('$', r'\$')
lines = [
    '// Generated by tool/import_transaction_keywords.py. Do not edit by hand.',
    '// Source: ' + source.name,
    '// SHA-256: ' + hashlib.sha256(source.read_bytes()).hexdigest(),
    '// Strength: 3 = strong, 2 = medium, 1 = contextual.',
    'const transactionKeywords = <(String, String, int)>[',
]
lines += [f'  ({quote(k)}, {quote(c)}, {s}),' for k, c, s in entries]
lines.append('];')
destination.parent.mkdir(parents=True, exist_ok=True)
destination.write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(f'Imported {len(entries)} keywords:', dict(collections.Counter(e[1] for e in entries)))
