"""Import only bank/wallet names and aliases from the supplied XLSX.

Workbook notes, links, and instructions are not imported or executed.
Uses only the Python standard library; rerun with the workbook path.
"""
import hashlib
import json
from pathlib import Path
import sys
import xml.etree.ElementTree as ET
import zipfile

source = Path(sys.argv[1])
destination = Path(__file__).resolve().parents[1] / 'lib/data/payment_sources.dart'
ns = {'s': 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}
entries = []
with zipfile.ZipFile(source) as archive:
    strings = []
    if 'xl/sharedStrings.xml' in archive.namelist():
        strings = [''.join(node.itertext()) for node in
                   ET.fromstring(archive.read('xl/sharedStrings.xml')).findall('s:si', ns)]
    for sheet in ('sheet1', 'sheet2'):
        rows = []
        for row in ET.fromstring(archive.read(f'xl/worksheets/{sheet}.xml')).findall('.//s:row', ns):
            cells = {}
            for cell in row.findall('s:c', ns):
                column = ''.join(c for c in cell.attrib['r'] if c.isalpha())
                value, inline = cell.find('s:v', ns), cell.find('s:is', ns)
                text = value.text if value is not None else ''.join(inline.itertext()) if inline is not None else ''
                cells[column] = strings[int(text)] if cell.get('t') == 's' else text
            rows.append(cells)
        assert rows[0]['B'] in ('Nama bank', 'Nama e-wallet')
        for row in rows[1:]:
            if not row.get('A', '').isdigit():
                continue
            name = row['B'].strip()
            # Wallet operators are not aliases: e.g. Sakuku's operator is BCA.
            columns = ('C', 'E', 'F', 'G') if sheet == 'sheet1' else ('D',)
            aliases = {name.lower()}
            for column in columns:
                aliases.update(a.strip().lower() for a in row.get(column, '').split(';') if a.strip())
            entries.append((name, sorted(aliases)))
assert len(entries) == 126, f'Expected 105 banks + 21 wallets, got {len(entries)}'
quote = lambda text: json.dumps(text, ensure_ascii=False).replace('$', r'\$')
lines = [
    '// Generated by tool/import_payment_sources.py. Do not edit by hand.',
    '// Source: ' + source.name,
    '// SHA-256: ' + hashlib.sha256(source.read_bytes()).hexdigest(),
    'const paymentSources = <(String, List<String>)>[',
]
for name, aliases in entries:
    lines.append(f'  ({quote(name)}, [{", ".join(map(quote, aliases))}]),')
lines.append('];')
destination.write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(f'Imported {len(entries)} payment sources.')
